DATASET:
  ROOT: 'data/'
  NAME: 'officehome'
  SOURCE_DOMAINS: ['Art', 'Clipart', 'Product', 'RealWorld']
  TARGET_DOMAINS: ['Art', 'Clipart', 'Product', 'RealWorld']
  NUM_CLASS: 65
  SOURCE_TRANSFORMS : ('Resize','RandomHorizontalFlip','RandomCrop','Normalize')
  TARGET_TRANSFORMS : ('Resize','RandomHorizontalFlip','RandomCrop','Normalize')

DATALOADER:
  BATCH_SIZE: 32

MODEL:
   NORMALIZE: True
   TEMP : 0.05

OPTIM:
  NAME: 'Adadelta'
  SOURCE_LR: 0.1
  BASE_LR_MULT: 0.1

TRAINER:
  MAX_EPOCHS: 40
  TRAIN_ON_SOURCE : False
  MAX_UDA_EPOCHS: 0

ADA:
  DA : 'ft'
  AL : 'random'
  ROUNDS : [10, 12, 14, 16, 18]
  BUDGET: 65.

SEED: 0  # 0,1,2,3,4 for five random experiments

